# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cf33089f2b3272db8cf0d648b04922a6808b14480d1a1e8e7dc23ede1c195223dfbde16bfc0bfcf3e037db94e6636db216adecb0c4cf8a45b89b91ff96ec4396

test:
  secret_key_base: adc675e57aaf7390c76fb127e301bae84ae8f38581547c2cec7010ef1a59e9431c5cbe479c64bdf733a8746d0fa01d49738b4273cf6c6cb8a420203d797a3bd9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
